const { withGradleProperties } = require('expo/config-plugins');

/**
 * Expo config plugin: raise the Gradle JVM memory.
 *
 * `android/` is regenerated by `expo prebuild`, and the default
 * `gradle.properties` ships with `-Xmx2048m -XX:MaxMetaspaceSize=512m`.
 * That OOMs (Metaspace) during Kotlin/KSP compilation of a release build in
 * this monorepo — especially when the `@react-native/gradle-plugin`
 * includeBuild recompiles (see the patch-package patch for Os.kt). Bumping the
 * heap and metaspace keeps release builds green.
 */
module.exports = function withGradleMemory(config) {
  return withGradleProperties(config, (cfg) => {
    const setProp = (key, value) => {
      const existing = cfg.modResults.find(
        (item) => item.type === 'property' && item.key === key
      );
      if (existing) {
        existing.value = value;
      } else {
        cfg.modResults.push({ type: 'property', key, value });
      }
    };

    setProp('org.gradle.jvmargs', '-Xmx4096m -XX:MaxMetaspaceSize=1024m');

    return cfg;
  });
};
